"""first commit

Revision ID: e157e07fd58a
Revises:
Create Date: 2023-11-05 13:57:33.468481

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e157e07fd58a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
